#!/usr/bin/env python3
"""Write the top of a release or beta page: which PR, which issues, what changed — #128.

Rob, 4 October: "I see build 100, no beta and no idea what PR it contains".
Every Heart FC Coach and Heart FC Beta page (#108 Q1; "Coaching App" and
"Coaching Beta" before v1) now opens with:

    Build N contains PR #M (linked)
    the issues that PR closes, with their titles
    two or three plain lines of what changed, from the PR description
    the iPhone status line
    (beta only) the PR's "## Beta test steps" section

What changed, in order of preference:
  1. a "## What changed" or "## Summary" section in the PR body — its first
     three lines (an author who wants control of the page writes one);
  2. otherwise the PR's own section headings, minus the process sections
     (Evidence, Docs, Known gaps, Beta test steps…), at most three, with the
     "#125:" prefix and "(8a3d531)" commit refs stripped;
  3. otherwise the PR's first plain paragraph.

Lookups go through `gh api` with the job's GITHUB_TOKEN. Any lookup that fails
DEGRADES: the page still publishes and says what could not be found. A notes
step must never be the reason an APK is not released.

    release_notes.py main SHA BUILD_NUMBER     # Heart FC Coach, after a squash merge
    release_notes.py beta PR_NUMBER BUILD_NUMBER
    release_notes.py demo SHA BUILD_LABEL DATE # #146: the whole demo page
    release_notes.py --self-test

#146 AC5, the demo page (`demo`): what it is (made-up data only), "Refreshed
from build N on DATE", how to install it, and that it never touches Heart FC
Coach. Build N is the Heart FC Coach release built from the same commit, found
the way ios.yml's attach job finds it (a full `v*` release targeting that
commit; by tag and commit, never by title, so old- and new-titled releases are
both found). The only listing of releases here, and it reads, never writes. With
none (main's build still running, or red), the page names the commit instead.

Prints markdown on stdout; warnings on stderr. Exit 0 unless the arguments are
wrong. Needs GITHUB_REPOSITORY.
"""

import json
import os
import re
import subprocess
import sys

# #108: Apple enrolment is complete; the TestFlight upload (#108 A) is not built.
IPHONE_STATUS = "iPhone: coming through TestFlight (#108); no upload yet"
# #108 G: the demo's iPhone counterpart is the TestFlight beta, which comes later.
DEMO_IPHONE = "iPhone: there is no iPhone build of the demo yet (#108 G)."
# #108 Q1: the GitHub release titles follow the home-screen names (ruling 40).
APP_NAME = "Heart FC Coach"
BETA_NAME = "Heart FC Beta"
SIMULATOR_LINE = ("Mac: an iPhone-simulator build (`.zip`) is attached below by the iOS workflow "
                  "when its build finishes; see \"Run it on a Mac\" in the README.")
CLOSES = re.compile(r"^\s*(?:closes|fixes|resolves)\s+#(\d+)\b", re.I | re.M)
CHANGED_SECTIONS = ("what changed", "summary")
PROCESS_SECTIONS = ("evidence", "docs", "known gap", "beta test steps", "test plan",
                    "risks", "not done", "self-test", "dry-run")
FOOTER = re.compile(r"^(?:---\s*$|🤖|_Generated by|https://claude\.ai/code)")
MAX_LINES = 3


# ---------------------------------------------------------------------------
# Pure: PR body -> pieces. The self-test exercises these without a network.
# ---------------------------------------------------------------------------

def closed_issues(body):
    seen = []
    for n in CLOSES.findall(body or ""):
        if int(n) not in seen:
            seen.append(int(n))
    return seen


def sections(body):
    """[(heading or None, [lines])] split on '## ' headings; footer dropped."""
    out = [(None, [])]
    for line in (body or "").replace("\r\n", "\n").split("\n"):
        if FOOTER.match(line.strip()):
            break
        m = re.match(r"^##\s+(.*?)\s*$", line)
        if m:
            out.append((m.group(1), []))
        else:
            out[-1][1].append(line)
    return out


def _clean_heading(h):
    h = re.sub(r"\s*\((?:[0-9a-f]{7,40}|commit [0-9a-f]{7,40})\)", "", h)   # (8a3d531)
    h = re.sub(r"^#\d+(?:\s+\w+)?\s*:\s*", "", h)                          # "#125: " / "#126 extended: "
    h = re.sub(r"\s+—\s+PO ruling.*$", "", h).strip()
    return h[:1].upper() + h[1:]


def _plain(line):
    line = re.sub(r"^\s*(?:[-*]|\d+\.)\s+", "", line).strip()
    return line


def what_changed(body):
    secs = sections(body)
    for heading, lines in secs:
        if heading and heading.strip().lower() in CHANGED_SECTIONS:
            got = [_plain(l) for l in lines if l.strip()]
            if got:
                return got[:MAX_LINES]
    heads = []
    for heading, _ in secs:
        if not heading or any(heading.lower().startswith(p) for p in PROCESS_SECTIONS):
            continue
        h = _clean_heading(heading)
        if h and h not in heads:
            heads.append(h)
    if heads:
        return heads[:MAX_LINES]
    intro = [l.strip() for l in secs[0][1] if l.strip() and not CLOSES.match(l)]
    return intro[:MAX_LINES]


def beta_test_steps(body):
    for heading, lines in sections(body):
        if heading and heading.strip().lower() == "beta test steps":
            text = "\n".join(lines).strip()
            return text or None
    return None


def render(kind, build, repo, pr, issues, changed, steps, problems):
    """pr: dict(number, title) or None. issues: [(n, title or None)]."""
    out = []
    if pr:
        url = f"https://github.com/{repo}/pull/{pr['number']}"
        out.append(f"## Build {build} contains [PR #{pr['number']}]({url})")
        out.append("")
        out.append(f"**{pr['title']}**")
    else:
        out.append(f"## Build {build}")
        out.append("")
        out.append("_Could not work out which pull request this build contains; see the changelog below._")
    out.append("")
    if issues:
        out.append("Closes:")
        for n, title in issues:
            out.append(f"- [#{n}](https://github.com/{repo}/issues/{n}) {title or '(title not found)'}")
        out.append("")
    elif pr:
        out.append("_This PR closes no issue (no \"Closes #N\" line in its description)._")
        out.append("")
    if changed:
        out.append("What changed:")
        out.extend(f"- {line}" for line in changed)
        out.append("")
    out.append(f"**{IPHONE_STATUS}**")
    out.append("")
    out.append(SIMULATOR_LINE)
    out.append("")
    if kind == "beta":
        out.append("## Beta test steps")
        out.append("")
        out.append(steps or "_The PR description has no \"## Beta test steps\" section._")
        out.append("")
    for p in problems:
        out.append(f"_Note: {p}_")
    if problems:
        out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Impure: GitHub lookups, each one allowed to fail.
# ---------------------------------------------------------------------------

def gh_json(path):
    r = subprocess.run(["gh", "api", path], capture_output=True, text=True, timeout=60)
    if r.returncode != 0:
        raise RuntimeError(f"gh api {path}: {(r.stderr or r.stdout).strip()[:200]}")
    return json.loads(r.stdout)


def build_notes(kind, ref, build, repo, fetch=gh_json):
    problems = []
    pr = None
    if kind == "main":
        try:
            pulls = fetch(f"repos/{repo}/commits/{ref}/pulls")
            merged = [p for p in pulls if p.get("merge_commit_sha") == ref] or pulls
            if merged:
                pr = merged[0]
            else:
                problems.append(f"no pull request is associated with commit {ref[:7]} (pushed directly?).")
        except Exception as e:  # degrade, never block the release
            problems.append(f"the pull-request lookup for {ref[:7]} failed ({e}).")
    else:
        try:
            pr = fetch(f"repos/{repo}/pulls/{ref}")
        except Exception as e:
            problems.append(f"the lookup of PR #{ref} failed ({e}).")
            pr = {"number": int(ref), "title": "(title not found)", "body": ""}
    body = (pr or {}).get("body") or ""
    issues = []
    for n in closed_issues(body):
        try:
            issues.append((n, fetch(f"repos/{repo}/issues/{n}").get("title")))
        except Exception as e:
            issues.append((n, None))
            problems.append(f"could not read issue #{n} ({e}).")
    for p in problems:
        print(f"warning: {p}", file=sys.stderr)
    return render(kind, build, repo, pr and {"number": pr["number"], "title": pr.get("title", "")},
                  issues, what_changed(body) if pr else [], beta_test_steps(body), problems)


# ---------------------------------------------------------------------------
# The demo page — #146 AC5. check_release.py --demo reads these phrases back.
# ---------------------------------------------------------------------------

DEMO_TITLE = f"{BETA_NAME} — demo"
DEMO_APK = "coaching-beta-demo.apk"
DEMO_MADE_UP = "Made-up data only."
DEMO_NEVER_TOUCHES = f"never touches {APP_NAME}"
INSTALL_NOTE = ("Download the `.apk` below on an Android phone and open it.\n"
                "Allow installation from this source when prompted — it is signed\n"
                "with the Android debug key, not a Play Store key.")
REFRESHED = re.compile(r"Refreshed from (?:build \d+|main at `[0-9a-f]{7}`) on \d{1,2} [A-Z][a-z]+ \d{4}")


def main_release_at(sha, repo, fetch):
    """(build number, url) of the full `v*` release built from SHA, or None."""
    for r in fetch(f"repos/{repo}/releases?per_page=30"):
        if (r.get("tag_name", "").startswith("v") and r.get("target_commitish") == sha
                and not r.get("prerelease") and not r.get("draft")):
            m = re.search(r"-build\.(\d+)$", r["tag_name"])
            if m:
                return int(m.group(1)), r.get("html_url", "")
    return None


def demo_notes(sha, label, date, repo, fetch=gh_json):
    """The whole demo page. DATE is 'D Month YYYY'. Never fails: a lookup
    that fails names the commit instead of the build."""
    try:
        found = main_release_at(sha, repo, fetch)
    except Exception as e:
        print(f"warning: the release lookup for {sha[:7]} failed ({e})", file=sys.stderr)
        found = None
    if found:
        n, url = found
        source = f"Refreshed from build {n} on {date}"
        detail = f"the code of [{APP_NAME} build {n}]({url}), with the test season loaded on first open."
    else:
        source = f"Refreshed from main at `{sha[:7]}` on {date}"
        detail = (f"main's code at that commit, which had no {APP_NAME} release when this "
                  "demo was refreshed, with the test season loaded on first open.")
    return "\n".join([
        f"## {DEMO_TITLE}",
        "",
        f"**{DEMO_MADE_UP}** It opens with a made-up squad (Ava, Ben, Cal…), two fixtures",
        "and a past season of nine matches already loaded, so anyone can see what the",
        "app does without typing anything. No real child is in it, and nothing on",
        "this page came from a phone: the test season is made on the phone, the first",
        "time the demo opens.",
        "",
        f"**{source}.** It is {detail}",
        "",
        "## Install it",
        "",
        INSTALL_NOTE,
        "",
        f"It installs as **{BETA_NAME}** (the orange icon), next to {APP_NAME}: it {DEMO_NEVER_TOUCHES}",
        f"or its data. It loads the test season only into an empty {BETA_NAME}. If",
        f"{BETA_NAME} is already on the phone, uninstall it first: Android will not",
        f"put an older build over a newer one, and a {BETA_NAME} with data keeps it.",
        f"{BETA_NAME} holds made-up test data only and has no backup. A demo installed",
        "before v1 (#108) is a different app with the old name: uninstall it too.",
        "",
        f"On the phone, the label at the foot of the first screen reads `{label}`.",
        "",
        f"**{DEMO_IPHONE}** Nor is there a simulator build of it.",
    ])


# ---------------------------------------------------------------------------
# Self-test: healthy cases first.
# ---------------------------------------------------------------------------

BODY_127 = """Closes #125
Closes #126
Closes #112

These are the three fixes from QA's retroactive verification (decision 6).

## #125: pills show total pitch time (8a3d531)
- `pillDetail` now shows goal plus outfield.

## #126: the match report dates a Play now match (b9f28b0)
- falls back to the first period.

## #112: the allowBackup gate has a self-test (a4bde15)
- moved into check_backup.py

## #126 extended: fixture cards too (43fb6a6) — PO ruling "approve 10"
- cards too

## Evidence (PR head 43fb6a6, run this session)
```
npx vitest run   708 passed
```

## Beta test steps
1. Install this PR's beta and add test data.
2. Move the keeper to the bench.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Not a real section
"""

BODY_SUMMARY = """Fixes #7

## What changed
- The clock survives a locked phone.
- Subs are announced a minute early.

## Evidence
ok
"""


def self_test():
    repo = "vanstoner/coaching-app"
    titles = {125: "Pills show outfield time", 126: "Play now has no date", 112: "Backup gate", 7: "Clock"}

    def fake(pr_body, fail_pulls=False, fail_issue=None, no_pr=False):
        def fetch(path):
            if path.endswith("/pulls") and "/commits/" in path:
                if fail_pulls:
                    raise RuntimeError("HTTP 403")
                return [] if no_pr else [{"number": 127, "title": "Fixes from QA", "body": pr_body,
                                          "merge_commit_sha": "abc1234def"}]
            if "/pulls/" in path:
                if fail_pulls:
                    raise RuntimeError("HTTP 404")
                return {"number": 127, "title": "Fixes from QA", "body": pr_body}
            n = int(path.rsplit("/", 1)[1])
            if n == fail_issue:
                raise RuntimeError("HTTP 404")
            return {"title": titles[n]}
        return fetch

    def has(*needles):
        return lambda md: all(n in md for n in needles)

    def lacks(*needles):
        return lambda md: not any(n in md for n in needles)

    def both(a, b):
        return lambda md: a(md) and b(md)

    link = f"[PR #127](https://github.com/{repo}/pull/127)"
    cases = [
        ("healthy main: PR, issues with titles, headings as changes, iPhone line",
         "main", "abc1234def", fake(BODY_127),
         both(has("## Build 101 contains " + link, "#125](https://github.com/vanstoner/coaching-app/issues/125) Pills show outfield time",
                  "#112", "- Pills show total pitch time", "- The allowBackup gate has a self-test",
                  "**" + IPHONE_STATUS + "**"),
              lacks("Beta test steps", "8a3d531", "ixture cards too", "Evidence", "Note:"))),
        ("healthy beta: same summary plus the test steps",
         "beta", "127", fake(BODY_127),
         both(has("## Build 101 contains " + link, "## Beta test steps", "2. Move the keeper to the bench.", IPHONE_STATUS),
              lacks("Generated with", "Not a real section", "Note:"))),
        ("healthy: a 'What changed' section wins over headings",
         "main", "abc1234def", fake(BODY_SUMMARY),
         both(has("- The clock survives a locked phone.", "#7](", "Clock"), lacks("- Evidence"))),
        ("degraded: PR lookup fails -> still a page, says so",
         "main", "abc1234def", fake(BODY_127, fail_pulls=True),
         has("## Build 101", "Could not work out which pull request", "_Note: the pull-request lookup", IPHONE_STATUS)),
        ("degraded: direct push, no PR",
         "main", "abc1234def", fake(BODY_127, no_pr=True),
         has("Could not work out", "no pull request is associated")),
        ("degraded: one issue title unreadable",
         "main", "abc1234def", fake(BODY_127, fail_issue=126),
         has("#126](https://github.com/vanstoner/coaching-app/issues/126) (title not found)", "could not read issue #126", "Pills show")),
        ("degraded beta: PR lookup fails, test steps say so",
         "beta", "127", fake(BODY_127, fail_pulls=True),
         has("contains [PR #127]", "lookup of PR #127 failed", "has no \"## Beta test steps\" section")),
        ("no Closes lines and no headings -> first paragraph, says no issue",
         "main", "abc1234def", fake("Bump the runner.\n\nSecond paragraph line."),
         has("closes no issue", "- Bump the runner.")),
    ]
    failed = 0
    for name, kind, ref, fetch, ok in cases:
        md = build_notes(kind, ref, "101", repo, fetch=fetch)
        good = ok(md)
        failed += not good
        print(f"  {'ok' if good else 'x '} {name}")
        if not good:
            print("    " + md.replace("\n", "\n    "))

    # #146 AC5: the demo page. Healthy first: main's release exists.
    sha = "abc1234def5678"
    rel = {"tag_name": "v1.0.0-build.153", "target_commitish": sha, "prerelease": False,
           "draft": False, "html_url": f"https://github.com/{repo}/releases/tag/v1.0.0-build.153"}

    def releases(*items, fail=False):
        def fetch(path):
            if fail:
                raise RuntimeError("HTTP 502")
            return list(items)
        return fetch

    other = dict(rel, target_commitish="0000000", tag_name="v1.0.0-build.150")
    # #108: a release from before v1, date-tagged, at the commit: still build N.
    dated = dict(rel, tag_name="v2026.10.06-build.153",
                 html_url=f"https://github.com/{repo}/releases/tag/v2026.10.06-build.153")
    demo_cases = [
        ("healthy demo: names build N, made-up data, install note, never touches Heart FC Coach",
         releases(other, rel),
         both(has("## Heart FC Beta — demo", DEMO_MADE_UP, "Refreshed from build 153 on 6 October 2026",
                  "[Heart FC Coach build 153](https://github.com/vanstoner/coaching-app/releases/tag/v1.0.0-build.153)",
                  INSTALL_NOTE, DEMO_NEVER_TOUCHES, "`demo (1.0.0, build 160)`", DEMO_IPHONE,
                  "It installs as **Heart FC Beta**"),
              both(lacks("waiting on Apple enrolment", "installs as **Coaching Beta**", "Coaching App"),
                   lambda md: REFRESHED.search(md) is not None))),
        ("healthy demo (switch): the build at the commit is an old date-tagged release",
         releases(dated), has("Refreshed from build 153 on 6 October 2026", "releases/tag/v2026.10.06-build.153")),
        ("degraded demo: no release at the commit yet -> names the commit",
         releases(other),
         both(has("Refreshed from main at `abc1234` on 6 October 2026", DEMO_MADE_UP, INSTALL_NOTE),
              lacks("build 150", "build 153"))),
        ("degraded demo: the lookup fails -> still a whole page",
         releases(fail=True), has("Refreshed from main at `abc1234`", DEMO_NEVER_TOUCHES)),
        ("demo: a prerelease (a PR beta) at the commit is not build N",
         releases(dict(rel, prerelease=True), dict(rel, tag_name="beta")),
         both(has("Refreshed from main at"), lacks("build 153"))),
        ("demo: the `demo` release itself is never taken for build N",
         releases(dict(rel, tag_name="demo", prerelease=True)), lacks("build 153", "Refreshed from build")),
    ]
    for name, fetch, ok in demo_cases:
        md = demo_notes(sha, "demo (1.0.0, build 160)", "6 October 2026", repo, fetch=fetch)
        good = ok(md)
        failed += not good
        print(f"  {'ok' if good else 'x '} {name}")
        if not good:
            print("    " + md.replace("\n", "\n    "))
    print(f"{len(cases) + len(demo_cases) - failed} expectation(s) passed, {failed} failed.")
    return 1 if failed else 0


def main(argv):
    if argv[1:] == ["--self-test"]:
        return self_test()
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    if len(argv) == 5 and argv[1] == "demo" and repo:
        print(demo_notes(argv[2], argv[3], argv[4], repo))
        return 0
    if len(argv) != 4 or argv[1] not in ("main", "beta") or not repo:
        print(__doc__, file=sys.stderr)
        return 2
    print(build_notes(argv[1], argv[2], argv[3], repo))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
